# Generated by Django 3.1.4 on 2024-11-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_des', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('reviews', models.CharField(max_length=100)),
            ],
        ),
    ]
