# Generated by Django 3.1.4 on 2024-12-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20241216_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
