# Generated by Django 3.1.4 on 2024-12-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='adrees',
        ),
    ]
