# Generated by Django 3.1.4 on 2024-12-23 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_user_profile_adrees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coustomer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='coustomer',
            new_name='Customer',
        ),
    ]
