# Generated by Django 3.1.4 on 2024-12-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20241223_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
