# Generated by Django 3.1.4 on 2024-12-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_hotel_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Customer',
            new_name='customer',
        ),
    ]
