# Generated by Django 3.1.4 on 2024-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20241224_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_des',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
