# Generated by Django 3.1.4 on 2025-01-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='image',
            new_name='room_pic',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
